In [1]:
# !pip install chromadb

In [2]:
import chromadb
from chromadb.config import Settings
from sentence_transformers import SentenceTransformer

In [3]:
# chromadb.config?

In [4]:
client = chromadb.Client(Settings(persist_directory="./chroma_store"))

In [5]:
collection = client.get_or_create_collection(name="my_collection")
collection2 = client.get_or_create_collection(name="legal_docs")
collection3 = client.get_or_create_collection(name="images")

In [6]:
documents = ["Chroma is the open-source AI application database. Batteries included.",
             "This is another document",
             """Store embeddings and their metadata
Vector search
Full-text search
Document storage
Metadata filtering
Multi-modal retrieval""",
             "Data ingestion is the firststep of building AI search system"]
ids = ["id1", "id2", "id3", "ram"]

In [7]:
["id"+str(i) for i in range(len(documents))]

['id0', 'id1', 'id2', 'id3']

In [115]:
model = SentenceTransformer("distilbert/distilbert-base-uncased-finetuned-sst-2-english")

WARNING:sentence_transformers.SentenceTransformer:No sentence-transformers model found with name distilbert/distilbert-base-uncased-finetuned-sst-2-english. Creating a new one with mean pooling.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert/distilbert-base-uncased-finetuned-sst-2-english
Key                   | Status     |  |
----------------------+------------+--+-
classifier.weight     | UNEXPECTED |  |
classifier.bias       | UNEXPECTED |  |
pre_classifier.bias   | UNEXPECTED |  |
pre_classifier.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
len(model.encode(documents).tolist()[0])

768

In [10]:
embeddings = model.encode(documents)

In [11]:
embeddings.shape

(4, 768)

In [12]:
#bm25

In [13]:
#ingest document+ embeddings into chromadb
collection.add(
    documents=documents,
    embeddings=embeddings,
    ids=ids
) #append, if id doesn't exist

In [14]:
query = "how does chroma enable semantic retrieval?"

In [15]:
query_embedding = model.encode([query])

In [16]:
collection.query(query_embeddings=query_embedding, n_results=3)

{'ids': [['id3', 'ram', 'id1']],
 'embeddings': None,
 'documents': [['Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
   'Data ingestion is the firststep of building AI search system',
   'Chroma is the open-source AI application database. Batteries included.']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[None, None, None]],
 'distances': [[76.8458480834961, 80.17295837402344, 199.04112243652344]]}

In [17]:
# cosine=highest simi,
# eclidean= highest score, lowest similar

In [19]:
embedding = model.encode(["good morning"])

In [20]:
collection.add(ids=["id5"], documents=["good morning"], embeddings=embedding)

In [21]:
collection.get()

{'ids': ['id1', 'id2', 'id3', 'ram', 'id5'],
 'embeddings': None,
 'documents': ['Chroma is the open-source AI application database. Batteries included.',
  'This is another document',
  'Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
  'Data ingestion is the firststep of building AI search system',
  'good morning'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None, None, None, None, None]}

In [22]:
embedding = model.encode(["gggggggggggggggggggg"])
collection.add(ids=["id5"], documents=["gggggggggggggggggggg"], embeddings=embedding)

In [23]:
collection.get()

{'ids': ['id1', 'id2', 'id3', 'ram', 'id5'],
 'embeddings': None,
 'documents': ['Chroma is the open-source AI application database. Batteries included.',
  'This is another document',
  'Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
  'Data ingestion is the firststep of building AI search system',
  'good morning'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None, None, None, None, None]}

In [113]:
collection.get()

{'ids': ['id1', 'id2', 'id3', 'ram', 'id8'],
 'embeddings': None,
 'documents': ['Chroma is the open-source AI application database. Batteries included.',
  'This is another document',
  'Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
  'Data ingestion is the firststep of building AI search system',
  'gggggggggggggggggggg'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None, None, None, None, None]}

In [116]:
embedding = model.encode(["gggggggggggggggggggg"])
collection.upsert(ids=["id5"], documents=["gggggggggggggggggggg"], embeddings=embedding, metadatas={"topic":"sports", "timestamp":"15/03/2026"})

In [117]:
collection.get()

{'ids': ['id1', 'id2', 'id3', 'ram', 'id8', 'id5'],
 'embeddings': None,
 'documents': ['Chroma is the open-source AI application database. Batteries included.',
  'This is another document',
  'Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
  'Data ingestion is the firststep of building AI search system',
  'gggggggggggggggggggg',
  'gggggggggggggggggggg'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None,
  None,
  None,
  None,
  None,
  {'topic': 'sports', 'timestamp': '15/03/2026'}]}

In [26]:
embedding = model.encode(["gggggggggggggggggggg"])
collection.add(ids=["id8"], documents=["gggggggggggggggggggg"], embeddings=embedding)

In [27]:
collection.get()

{'ids': ['id1', 'id2', 'id3', 'ram', 'id5', 'id8'],
 'embeddings': None,
 'documents': ['Chroma is the open-source AI application database. Batteries included.',
  'This is another document',
  'Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
  'Data ingestion is the firststep of building AI search system',
  'gggggggggggggggggggg',
  'gggggggggggggggggggg'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None, None, None, None, None, None]}

In [28]:
embedding = model.encode(["gggggggggggggggggggg"])
collection.add(documents=["gggggggggggggggggggg"], embeddings=embedding)

TypeError: Collection.add() missing 1 required positional argument: 'ids'

In [29]:
collection.delete("id5")

{'deleted': 1}

In [30]:
collection.get()

{'ids': ['id1', 'id2', 'id3', 'ram', 'id8'],
 'embeddings': None,
 'documents': ['Chroma is the open-source AI application database. Batteries included.',
  'This is another document',
  'Store embeddings and their metadata\nVector search\nFull-text search\nDocument storage\nMetadata filtering\nMulti-modal retrieval',
  'Data ingestion is the firststep of building AI search system',
  'gggggggggggggggggggg'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None, None, None, None, None]}

# FAISS

In [34]:
# !pip install faiss-cpu

In [35]:
import faiss

In [38]:
import pandas as pd
df = pd.read_csv("olympics.csv")

In [55]:
df.head(10)

,Name,Sport,Country,Medal,combined
0,Cristiano Ronaldo,Athletics,China,Gold,Cristiano Ronaldo Athletics China Gold
1,Usain Bolt,Gymnastics,India,Bronze,Usain Bolt Gymnastics India Bronze
2,Michael Phelps,Wrestling,Russia,Silver,Michael Phelps Wrestling Russia Silver
3,Novak Djokovic,Football,Brazil,Bronze,Novak Djokovic Football Brazil Bronze
4,Mo Farah,Gymnastics,Germany,Bronze,Mo Farah Gymnastics Germany Bronze
5,Katie Ledecky,Cycling,Kenya,Gold,Katie Ledecky Cycling Kenya Gold
6,Katie Ledecky,Boxing,Germany,Gold,Katie Ledecky Boxing Germany Gold
7,Simone Biles,Tennis,Jamaica,Bronze,Simone Biles Tennis Jamaica Bronze
8,Novak Djokovic,Wrestling,China,Gold,Novak Djokovic Wrestling China Gold
9,Usain Bolt,Football,China,Gold,Usain Bolt Football China Gold

In [39]:
df.columns

Index(['Name', 'Sport', 'Country', 'Medal'], dtype='object')

In [41]:
df["combined"] = df["Name"]+" "+df["Sport"]+" "+df["Country"]+" "+df["Medal"]

In [88]:
model = SentenceTransformer("all-minilm-l6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-minilm-l6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [89]:
embed = model.encode(df["combined"])

In [90]:
np.round(embed[0],2)

array([-0.02,  0.08, -0.02, -0.02,  0.04,  0.  ,  0.13,  0.08, -0.01,
        0.01,  0.  , -0.09, -0.03,  0.07,  0.  ,  0.04, -0.01,  0.03,
       -0.02, -0.06,  0.03, -0.05, -0.06,  0.03, -0.09,  0.02,  0.01,
        0.07, -0.08,  0.02, -0.03, -0.03,  0.04,  0.02, -0.08,  0.05,
       -0.03,  0.04, -0.01,  0.01,  0.01, -0.07,  0.05, -0.04,  0.04,
        0.03,  0.05, -0.03,  0.03,  0.03, -0.01,  0.05, -0.02, -0.01,
        0.08,  0.08,  0.06, -0.03,  0.01,  0.  , -0.01,  0.02, -0.  ,
       -0.01,  0.03, -0.09, -0.06,  0.04, -0.03,  0.05,  0.08,  0.02,
       -0.05,  0.01, -0.03,  0.05, -0.03,  0.01,  0.05, -0.03,  0.02,
       -0.12, -0.01, -0.06,  0.09,  0.01,  0.06, -0.05,  0.02, -0.03,
        0.02,  0.03, -0.06,  0.04, -0.03,  0.02, -0.  , -0.03, -0.06,
        0.08,  0.04,  0.09,  0.08,  0.02,  0.04, -0.01, -0.04,  0.16,
        0.07,  0.07, -0.02, -0.01, -0.01, -0.02, -0.06,  0.03, -0.13,
        0.03, -0.06,  0.05, -0.  , -0.  ,  0.  ,  0.01, -0.02, -0.02,
        0.03,  0.  , -0.06,  0.03,  0.03, -0.03, -0.08,  0.01, -0.  ,
        0.01, -0.03, -0.08, -0.01,  0.07, -0.03,  0.04,  0.03,  0.05,
        0.  , -0.09, -0.01,  0.08,  0.05,  0.01,  0.02, -0.01,  0.  ,
        0.06, -0.  , -0.07, -0.02,  0.01,  0.02,  0.03, -0.05, -0.03,
       -0.  ,  0.02, -0.04, -0.03, -0.07,  0.01,  0.09, -0.07, -0.03,
       -0.03, -0.04, -0.  ,  0.02,  0.03,  0.03, -0.04, -0.06,  0.02,
        0.  , -0.03,  0.03, -0.12,  0.01, -0.04,  0.  , -0.06,  0.01,
        0.01, -0.08,  0.1 , -0.13,  0.01, -0.  , -0.05,  0.01, -0.05,
        0.03, -0.  ,  0.02, -0.02, -0.03, -0.02, -0.03, -0.06, -0.01,
        0.02, -0.07,  0.06,  0.03,  0.03, -0.05,  0.07,  0.01,  0.03,
        0.01,  0.03, -0.03, -0.06,  0.  , -0.05, -0.05, -0.  , -0.04,
        0.01,  0.09,  0.06,  0.12,  0.04,  0.02,  0.11, -0.05, -0.01,
        0.08, -0.07,  0.  ,  0.  ,  0.03,  0.07,  0.07,  0.12, -0.1 ,
        0.01,  0.06,  0.03,  0.02, -0.02, -0.1 , -0.02,  0.09, -0.05,
       -0.04, -0.03, -0.02,  0.04, -0.04,  0.02, -0.04,  0.02, -0.03,
        0.04,  0.03,  0.11,  0.06,  0.  , -0.02,  0.13,  0.01, -0.05,
       -0.1 ,  0.02,  0.03,  0.07, -0.03, -0.04, -0.07, -0.03, -0.03,
        0.04, -0.03, -0.  , -0.03,  0.03, -0.04,  0.02, -0.02,  0.05,
       -0.03,  0.06,  0.02,  0.12, -0.08, -0.07, -0.01, -0.01,  0.03,
        0.  , -0.05,  0.04, -0.06,  0.18,  0.08, -0.01,  0.02, -0.05,
        0.02, -0.04, -0.03, -0.  , -0.02, -0.07, -0.01, -0.02,  0.03,
        0.  ,  0.03, -0.1 ,  0.01, -0.  ,  0.01, -0.03,  0.04, -0.02,
       -0.01,  0.11, -0.01, -0.05,  0.06,  0.01,  0.02, -0.02, -0.06,
       -0.01, -0.1 ,  0.  , -0.01,  0.12,  0.03,  0.11,  0.  , -0.02,
       -0.  , -0.05, -0.  , -0.07, -0.09, -0.03, -0.07, -0.09,  0.02,
       -0.06,  0.02, -0.03,  0.01,  0.09,  0.05, -0.08, -0.09, -0.08,
        0.06, -0.04, -0.04, -0.02,  0.13, -0.07, -0.03, -0.07, -0.01,
        0.05, -0.09,  0.03,  0.03, -0.1 ,  0.01,  0.02,  0.02, -0.08,
       -0.02,  0.01,  0.06, -0.09,  0.01,  0.  ], dtype=float32)

In [91]:
df.shape

(100, 5)

In [92]:
embed.shape

(100, 384)

In [93]:
import numpy as np
embed = np.array(embed).astype('float32')

In [94]:
dimension = embed.shape[1]

In [95]:
eu = faiss.IndexFlatL2(dimension)
eu.add(embed)

In [96]:
faiss.write_index(eu, "eu_index")

In [97]:
i1 = faiss.read_index("eu_index")

In [98]:
query = "can we get top swimmers name"

In [99]:
q_emb = model.encode([query]).astype("float32")

In [100]:
distances, indices = i1.search(q_emb, k=2)

In [101]:
distances

array([[0.9697888, 1.0797161]], dtype=float32)

In [102]:
indices

array([[51, 13]])

In [103]:
df["combined"].iloc[indices[0]]

51    Yohan Blake Swimming Brazil Bronze
13     Usain Bolt Swimming Canada Bronze
Name: combined, dtype: object

In [104]:
quantizer = faiss.IndexFlatIP(dimension)
clustering = faiss.IndexIVFFlat(quantizer, dimension, 10)
clustering.train(embed)
clustering.add(embed)

In [109]:
D, I = clustering.search(q_emb, k=2)

In [110]:
df["combined"].iloc[I[0]]

79     Katie Ledecky Athletics USA Bronze
25    Katie Ledecky Tennis Jamaica Bronze
Name: combined, dtype: object

In [111]:
hnsw = faiss.IndexHNSWFlat(dimension, 32)
hnsw.add(embed)

In [112]:
hnsw.search(q_emb, k=2)

(array([[0.9697888, 1.0797161]], dtype=float32), array([[51, 13]]))

In [ ]:
faiss.Inde